// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsflFqxJA2Ae_n_9wYGWKpk3lVtvwS7EA',
    appId: '1:419833567301:web:b1feb098cd1edb15582b2c',
    messagingSenderId: '419833567301',
    projectId: 'first-app-f9285',
    authDomain: 'first-app-f9285.firebaseapp.com',
    databaseURL: 'https://first-app-f9285-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-f9285.firebasestorage.app',
    measurementId: 'G-Q7K2XFJKJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfs9gLg3wnW1D-ika1vZpPu93Qn3mC-7E',
    appId: '1:419833567301:android:731984b0123429df582b2c',
    messagingSenderId: '419833567301',
    projectId: 'first-app-f9285',
    databaseURL: 'https://first-app-f9285-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-f9285.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaQtqzlf2GPbZPnB8Cq5OnkME_X-oQLb8',
    appId: '1:419833567301:ios:fe796d0eb47adf69582b2c',
    messagingSenderId: '419833567301',
    projectId: 'first-app-f9285',
    databaseURL: 'https://first-app-f9285-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-f9285.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaQtqzlf2GPbZPnB8Cq5OnkME_X-oQLb8',
    appId: '1:419833567301:ios:fe796d0eb47adf69582b2c',
    messagingSenderId: '419833567301',
    projectId: 'first-app-f9285',
    databaseURL: 'https://first-app-f9285-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-f9285.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsflFqxJA2Ae_n_9wYGWKpk3lVtvwS7EA',
    appId: '1:419833567301:web:e2ee08338efff9ff582b2c',
    messagingSenderId: '419833567301',
    projectId: 'first-app-f9285',
    authDomain: 'first-app-f9285.firebaseapp.com',
    databaseURL: 'https://first-app-f9285-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-f9285.firebasestorage.app',
    measurementId: 'G-CXMRK7WGYR',
  );
}
